import { Montserrat } from "next/font/google";
// import "@/style/globals.css";

const Monst = Montserrat({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={Monst.className}>{children}</body>
        </html>
    );
}
